## Global Name
name: ""

## Azure Active Directory Security
security:
  type: "AZURE"
  azure:
    appIdURI: ""
    appClientId: ""
    appTenantId: ""
    appSecret: ""

## Terraform Storage
storage:
  azure:
    storageAccountName: ""
    storageAccountResourceGroup: ""
    storageAccountAccessKey: ""

## API properties
api:
  enabled: true
  version: ""
  replicaCount: ""
  properties:
    databaseType: ""
    databaseHostname: ""
    databaseName: ""
    databaseUser: ""
    databasePassword: ""

## Executor properties
executor:
  enabled: true
  version: ""
  replicaCount: ""
  properties:
    toolsRepository: "https://github.com/AzBuilder/terrakube-extensions"
    toolsBranch: "main"
    terraformStateType: "AzureTerraformStateImpl"
    terraformOutputType: "AzureTerraformOutputImpl"

## Registry properties
registry:
  enabled: true
  version: ""
  replicaCount: ""

## UI Properties
ui:
  enabled: true
  version: ""
  replicaCount: ""

## Ingress properties
ingress:
  useTls: true
  ui:
    enabled: true
    domain: ""
    path: ""
    pathType: ""
    annotations: {}
  api:
    enabled: true
    domain: ""
    path: ""
    pathType: ""
    annotations: {}
  registry:
    enabled: true
    domain: ""
    path: ""
    pathType: ""
    annotations: {}
