## Global Name
name: ""

## Azure Active Directory Security
security:
  dexIssuerUri: ""
  adminGroup: "TERRAKUBE_ADMIN"
  azure:
    appIdURI: ""
    appClientId: ""
    appTenantId: ""
    appSecret: ""

## Terraform Storage
storage:
  azure:
    storageAccountName: ""
    storageAccountResourceGroup: ""
    storageAccountAccessKey: ""
  aws:
    accessKey: ""
    secretKey: ""
    bucketName: ""
    region: ""

## API properties
api:
  enabled: true
  version: ""
  replicaCount: ""
  serviceType: ""
  resources: {}
  properties:
    databaseType: ""
    databaseHostname: ""
    databaseName: ""
    databaseUser: ""
    databasePassword: ""

## Executor properties
executor:
  enabled: true
  version: ""
  replicaCount: ""
  serviceType: ""
  resources: {}
  properties:
    toolsRepository: "https://github.com/AzBuilder/terrakube-extensions"
    toolsBranch: "main"
    terraformStateType: ""
    terraformOutputType: ""

## Registry properties
registry:
  enabled: true
  version: ""
  replicaCount: ""
  serviceType: ""
  resources: {}

## UI Properties
ui:
  enabled: true
  version: ""
  replicaCount: ""
  serviceType: ""
  resources: {}

## Ingress properties
ingress:
  useTls: true
  ui:
    enabled: true
    domain: ""
    path: ""
    pathType: ""
    annotations: {}
  api:
    enabled: true
    domain: ""
    path: ""
    pathType: ""
    annotations: {}
  registry:
    enabled: true
    domain: ""
    path: ""
    pathType: ""
    annotations: {}
