{{- if and (eq .Values.ingress.controller "gke") .Values.ingress.gke.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.name }}-shared
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.global-static-ip-name: {{ .Values.ingress.gke.sharedLoadBalancer.staticIPName }}
    {{- if .Values.ingress.gke.managedCertificate.create }}
    networking.gke.io/managed-certificates: {{ .Values.name }}-certificate
    {{- end }}
    {{- if .Values.ingress.gke.frontendConfig.create }}
    networking.gke.io/v1beta1.FrontendConfig: {{ .Values.name }}-frontend-config
    {{- end }}
    {{- range $key, $value := .Values.ingress.gke.annotations }}
    {{ $key }}: {{ tpl (toString $value) $ | quote }}
    {{- end }}
spec:
  ingressClassName: gce
  rules:
    {{- if .Values.ingress.ui.enabled }}
    - host: {{ .Values.ingress.ui.domain }}
      http:
        paths:
          - path: {{ .Values.ingress.ui.path }}
            pathType: {{ .Values.ingress.ui.pathType }}
            backend:
              service:
                name: {{ .Values.name }}-ui-service
                port:
                  number: 8080
    {{- end }}
    {{- if .Values.ingress.api.enabled }}
    - host: {{ .Values.ingress.api.domain }}
      http:
        paths:
          - path: {{ .Values.ingress.api.path }}
            pathType: {{ .Values.ingress.api.pathType }}
            backend:
              service:
                name: {{ .Values.name }}-api-service
                port:
                  number: 8080
    {{- end }}
    {{- if .Values.ingress.registry.enabled }}
    - host: {{ .Values.ingress.registry.domain }}
      http:
        paths:
          - path: {{ .Values.ingress.registry.path }}
            pathType: {{ .Values.ingress.registry.pathType }}
            backend:
              service:
                name: {{ .Values.name }}-registry-service
                port:
                  number: 8075
    {{- end }}
    {{- if .Values.ingress.dex.enabled }}
    - host: {{ .Values.ingress.dex.domain }}
      http:
        paths:
          - path: {{ .Values.ingress.dex.path }}
            pathType: {{ .Values.ingress.dex.pathType }}
            backend:
              service:
                name: {{ .Release.Name }}-dex
                port:
                  number: 5556
    {{- end }}
    {{- if .Values.ingress.executor.enabled }}
    - host: {{ .Values.ingress.executor.domain }}
      http:
        paths:
          - path: {{ .Values.ingress.executor.path }}
            pathType: {{ .Values.ingress.executor.pathType }}
            backend:
              service:
                name: {{ .Values.name }}-executor-service
                port:
                  number: 8090
    {{- end }}
  {{- if .Values.ingress.useTls }}
  tls:
    {{- if .Values.ingress.ui.enabled }}
    - hosts:
        - {{ .Values.ingress.ui.domain }}
      secretName: {{ .Values.ingress.ui.tlsSecretName }}
    {{- end }}
    {{- if .Values.ingress.api.enabled }}
    - hosts:
        - {{ .Values.ingress.api.domain }}
      secretName: {{ .Values.ingress.api.tlsSecretName }}
    {{- end }}
    {{- if .Values.ingress.registry.enabled }}
    - hosts:
        - {{ .Values.ingress.registry.domain }}
      secretName: {{ .Values.ingress.registry.tlsSecretName }}
    {{- end }}
    {{- if .Values.ingress.dex.enabled }}
    - hosts:
        - {{ .Values.ingress.dex.domain }}
      secretName: {{ .Values.ingress.dex.tlsSecretName }}
    {{- end }}
    {{- if .Values.ingress.executor.enabled }}
    - hosts:
        - {{ .Values.ingress.executor.domain }}
      secretName: {{ .Values.ingress.executor.tlsSecretName }}
    {{- end }}
  {{- end }}
{{- end }}