{{- if and (eq .Values.ingress.controller "gke") .Values.ingress.gke.enabled .Values.ingress.gke.backendConfig.create .Values.ingress.registry.enabled }}
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: {{ .Values.name }}-registry-backend-config
  labels:
    {{- include "terrakube.labels" . | nindent 4 }}
spec:
  timeoutSec: {{ .Values.ingress.gke.backendConfig.timeout }}
  {{- if .Values.ingress.gke.backendConfig.registrySecurityPolicy }}
  securityPolicy:
    name: {{ .Values.ingress.gke.backendConfig.registrySecurityPolicy }}
  {{- end }}
  healthCheck:
    checkIntervalSec: 15
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 2
    type: HTTP
    requestPath: "/actuator/health"
    port: 8075
{{- end }}