{{- if .Values.ui.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: terrakube-ui
  labels:
    app: terrakube-ui
spec:
  replicas: {{ .Values.ui.replicaCount }}
  selector:
    matchLabels:
      app: terrakube-ui
  template:
    metadata:
      labels:
        app: terrakube-ui
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/secrets-ui.yaml") . | sha256sum }}
    spec:
      containers:
      - name: terrakube-ui
        image: azbuilder/terrakube-ui:{{ default .Chart.AppVersion .Values.ui.version }}
        volumeMounts:
        - name: ui-config
          mountPath: "/app/env-config.js"
          subPath: "env-config.js"
          readOnly: true
        {{- if .Values.ui.resources }}
        resources: {{- toYaml .Values.ui.resources | nindent 12 }}
        {{- end }}
        ports:
        - containerPort: 8080
        envFrom:
        - secretRef:
            name: terrakube-ui-secrets
      {{- with .Values.ui.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ui.tolerations }}
      tolerations:
        {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.ui.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: ui-config
        secret:
          secretName: terrakube-ui-secrets
          items:
          - key: env-config.js
            path: env-config.js
{{ end }}