{{- if .Values.api.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: terrakube-api
  labels:
    app: terrakube-api
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      app: terrakube-api
  template:
    metadata:
      labels:
        app: terrakube-api
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/secrets-api.yaml") . | sha256sum }}
    spec:
      containers:
      - name: terrakube-api
        image: azbuilder/api-server:{{ default .Chart.AppVersion .Values.api.version }}
        {{- if .Values.api.resources }}
        resources: {{- toYaml .Values.api.resources | nindent 12 }}
        {{- end }}
        ports:
        - containerPort: 8080
        {{- with .Values.api.env }}
        env:
        {{- toYaml . | nindent 8 }}
        {{- end }}
        volumeMounts:
          {{- with .Values.api.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
        envFrom:
        - secretRef:
            name: terrakube-api-secrets
        startupProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          failureThreshold: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 120
          periodSeconds: 10
      {{- with .Values.api.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.tolerations }}
      tolerations:
        {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.api.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.volumes }}
      volumes:
      {{- toYaml . | nindent 6 }}
      {{- end }}
{{ end }}