{{- if .Values.security.useOpenLDAP -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: terrakube-openldap
  labels:
    {{- include "terrakube.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "terrakube-openldap.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "terrakube-openldap.labels" . | nindent 8 }}
        {{- with .Values.openldap.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        {{- with .Values.openldap.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        checksum/config: {{ include (print $.Template.BasePath "/secret-openldap.yaml") . | sha256sum }}
    spec:
      {{- with .Values.openldap.imagePullSecrets | default .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.openldap.initContainers }}
      initContainers:
        {{- toYaml . | nindent 6 }}
      {{- end }}
      containers:
      - name: terrakube-openldap
        image: {{ .Values.openldap.image }}:{{ .Values.openldap.version }}
        env:
        - name: LDAP_ADMIN_USERNAME
          value: {{ .Values.openldap.adminUser }}
        - name: LDAP_ADMIN_PASSWORD
          value: {{ .Values.openldap.adminPass }}
        - name: LDAP_ROOT
          value: {{ .Values.openldap.baseRoot }}
        - name: LDAP_CUSTOM_LDIF_DIR
          value: "/ldifs"
        ports:
        - containerPort: 1389
        volumeMounts:
        - name: openldap-config
          mountPath: "/ldifs/config-ldap.ldif"
          subPath: "config-ldap.ldif"
          readOnly: true
        {{- with .Values.openldap.containerSecurityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      volumes:
        - name: openldap-config
          secret:
            secretName: {{ .Values.security.ldapConfigSecretName }}
            items:
            - key: "config-ldap.ldif"
              path: "config-ldap.ldif"
      {{- with .Values.openldap.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{ end }}
