{{- if .Values.executor.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: terrakube-executor
  labels:
    app: terrakube-executor
spec:
  replicas: {{ .Values.executor.replicaCount }}
  selector:
    matchLabels:
      app: terrakube-executor
  template:
    metadata:
      labels:
        app: terrakube-executor
        {{- with .Values.executor.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/secrets-executor.yaml") . | sha256sum }}
        {{- with .Values.executor.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.executor.imagePullSecrets | default .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.executor.initContainers }}
      initContainers:
        {{- toYaml . | nindent 6 }}
      {{- end }}
      containers:
      - name: terrakube-executor
        image: {{ .Values.executor.image }}:{{ default .Chart.AppVersion .Values.executor.version }}
        {{- if .Values.executor.resources }}
        resources: {{- toYaml .Values.executor.resources | nindent 12 }}
        {{- end }}
        ports:
        - containerPort: 8090
        {{- with .Values.executor.env }}
        env:
        {{- toYaml . | nindent 8 }}
        {{- end }}
        volumeMounts:
          {{- with .Values.executor.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
        envFrom:
        {{- range .Values.executor.secrets }}
            - secretRef:
                name: {{ . | quote }}
        {{- end }}
        startupProbe:
          httpGet:
            path: /actuator/health
            port: 8090
          failureThreshold: {{ .Values.executor.startupProbe.failureThreshold }}
          periodSeconds: {{ .Values.executor.startupProbe.periodSeconds }}
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8090
          initialDelaySeconds: {{ .Values.executor.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.executor.livenessProbe.periodSeconds }}
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8090
          initialDelaySeconds: {{ .Values.executor.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.executor.readinessProbe.periodSeconds }}
        {{- with .Values.executor.containerSecurityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- with .Values.executor.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.executor.tolerations }}
      tolerations:
        {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.executor.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.executor.volumes }}
      volumes:
      {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.executor.serviceAccountName }}
      serviceAccountName: {{ quote . }}
      {{- end }}
      {{- with .Values.executor.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{ end }}
