{{- if .Values.ui.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: terrakube-ui
  labels:
    {{- include "terrakube.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.ui.replicaCount }}
  selector:
    matchLabels:
      {{- include "terrakube-ui.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "terrakube-ui.labels" . | nindent 8 }}
        {{- with .Values.ui.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        {{- with .Values.ui.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        checksum/configmap: {{ include (print $.Template.BasePath "/configMap-ui.yaml") . | sha256sum }}
        checksum/config: {{ include (print $.Template.BasePath "/secrets-ui.yaml") . | sha256sum }}
    spec:
      {{- with .Values.ui.imagePullSecrets | default .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ui.initContainers }}
      initContainers:
        {{- toYaml . | nindent 6 }}
      {{- end }}
      containers:
      - name: terrakube-ui
        image: {{ .Values.ui.image }}:{{ default .Chart.AppVersion .Values.ui.version }}
        volumeMounts:
        - name: ui-config
          mountPath: "/app/env-config.js"
          subPath: "env-config.js"
          readOnly: true
        - name: ui-web-config
          mountPath: "/bitnami/nginx/conf/server_blocks/my_server_block.conf"
          subPath: my_server_block.conf
          readOnly: true
        {{- if .Values.ui.resources }}
        resources: {{- toYaml .Values.ui.resources | nindent 12 }}
        {{- end }}
        ports:
        - containerPort: 8080
        envFrom:
        - secretRef:
            name: terrakube-ui-secrets
        {{- with .Values.ui.containerSecurityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- with .Values.ui.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ui.tolerations }}
      tolerations:
        {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.ui.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: ui-config
        secret:
          secretName: terrakube-ui-secrets
          items:
          - key: env-config.js
            path: env-config.js
      - name: ui-web-config
        configMap:
          name: terrakube-ui
      {{- with .Values.ui.serviceAccountName }}
      serviceAccountName: {{ quote . }}
      {{- end }}
      {{- with .Values.ui.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{ end }}
