{{- if .Values.api.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: terrakube-api
  labels:
    {{- include "terrakube.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      {{- include "terrakube-api.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "terrakube-api.labels" . | nindent 8 }}
        {{- with .Values.api.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        {{- with .Values.api.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        checksum/config: {{ include (print $.Template.BasePath "/secrets-api.yaml") . | sha256sum }}
{{- if .Values.api.otel.enabled }}
        checksum/otel-config: {{ include (print $.Template.BasePath "/otel-api.yaml") . | sha256sum }}
{{- end }}
    spec:
      {{- with .Values.api.imagePullSecrets | default .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.initContainers }}
      initContainers:
        {{- toYaml . | nindent 6 }}
      {{- end }}
      containers:
      - name: terrakube-api
        image: {{ .Values.api.image }}:{{ default .Chart.AppVersion .Values.api.version }}
        {{- if .Values.api.resources }}
        resources: {{- toYaml .Values.api.resources | nindent 12 }}
        {{- end }}
        ports:
        - name: http
          containerPort: 8080
        {{- if and .Values.api.otel.enabled .Values.api.otel.metrics }}
        - name: metrics
          containerPort: {{ .Values.api.otel.metrics.port | default "9464" }}
        {{- end }}
        {{- with .Values.api.env }}
        env:
        {{- toYaml . | nindent 8 }}
        {{- end }}
        volumeMounts:
          {{- with .Values.api.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
        envFrom:
        {{- range .Values.api.secrets }}
        - secretRef:
            name: {{ . | quote }}
        {{- end }}
        {{- if .Values.api.otel.enabled}}
        - configMapRef:
            name: "terrakube-api-otel-config"
        {{- end }}
        startupProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30  # Increased from default
          periodSeconds: 10
          failureThreshold: 30     # Increased to give more startup time
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: http
          initialDelaySeconds: {{ .Values.api.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.api.livenessProbe.periodSeconds }}
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: http
          initialDelaySeconds: {{ .Values.api.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.api.readinessProbe.periodSeconds }}
        {{- with .Values.api.containerSecurityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- with .Values.api.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.tolerations }}
      tolerations:
        {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.api.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.volumes }}
      volumes:
      {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.api.serviceAccountName }}
      serviceAccountName: {{ quote . }}
      {{- end }}
      {{- with .Values.api.automountServiceAccountToken }}
      automountServiceAccountToken: {{ . }}
      {{- end }}
      {{- with .Values.api.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{ end }}
