{{- if .Values.ingress.executor.enabled }}
{{- if eq .Values.ingress.controller "generic" }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.name }}-executor
  labels:
    app: {{ .Values.name }}-executor
  {{- with .Values.ingress.executor.annotations }}
  annotations:
    {{- range $key, $value := . }}
    {{ $key }}: {{ tpl (toString $value) $ | quote }}
    {{- end }}
  {{- end }}
spec:
  {{- if .Values.ingress.executor.ingressClassName }}
  ingressClassName: {{ .Values.ingress.executor.ingressClassName }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.executor.domain }}
      http:
        paths:
          - path: {{ .Values.ingress.executor.path }}
            pathType: {{ .Values.ingress.executor.pathType }}
            backend:
              service:
                name: {{ .Values.name }}-executor-service
                port:
                  number: 8090
  {{- if .Values.ingress.useTls }}
  tls:
    - hosts:
      {{- if .Values.ingress.includeTlsHosts }}
        - {{ .Values.ingress.executor.domain }}
      {{- end }}
      secretName: {{ .Values.ingress.executor.tlsSecretName }}
  {{- end }}
{{- else if and (eq .Values.ingress.controller "aws") .Values.ingress.aws.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.name }}-executor
  labels:
    app: {{ .Values.name }}-executor
  annotations:
    {{- range $key, $value := .Values.ingress.aws.annotations }}
    {{ $key }}: {{ tpl (toString $value) $ | quote }}
    {{- end }}
    {{- if .Values.ingress.aws.certificateArn }}
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.ingress.aws.certificateArn }}
    {{- end }}
    {{- range $key, $value := .Values.ingress.executor.annotations }}
    {{ $key }}: {{ tpl (toString $value) $ | quote }}
    {{- end }}
spec:
  rules:
    - host: {{ .Values.ingress.executor.domain }}
      http:
        paths:
          - path: {{ .Values.ingress.executor.path }}
            pathType: {{ .Values.ingress.executor.pathType }}
            backend:
              service:
                name: {{ .Values.name }}-executor-service
                port:
                  number: 8090
{{- else if and (eq .Values.ingress.controller "gke") .Values.ingress.gke.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.name }}-executor
  labels:
    app: {{ .Values.name }}-executor
  annotations:
    {{- range $key, $value := .Values.ingress.gke.annotations }}
    {{ $key }}: {{ tpl (toString $value) $ | quote }}
    {{- end }}
    {{- if .Values.ingress.gke.sharedLoadBalancer.enabled }}
    {{- if .Values.ingress.gke.sharedLoadBalancer.staticIPName }}
    kubernetes.io/ingress.global-static-ip-name: {{ .Values.ingress.gke.sharedLoadBalancer.staticIPName }}
    {{- else if .Values.ingress.gke.sharedLoadBalancer.staticIPAddress }}
    kubernetes.io/ingress.global-static-ip: {{ .Values.ingress.gke.sharedLoadBalancer.staticIPAddress }}
    {{- end }}
    {{- end }}
    {{- if .Values.ingress.gke.managedCertificate.create }}
    networking.gke.io/managed-certificates: {{ .Values.name }}-certificate
    {{- else if and .Values.ingress.gke.managedCertificate.useExisting .Values.ingress.gke.managedCertificate.existingCertName }}
    networking.gke.io/managed-certificates: {{ .Values.ingress.gke.managedCertificate.existingCertName }}
    {{- end }}
    {{- range $key, $value := .Values.ingress.executor.annotations }}
    {{ $key }}: {{ tpl (toString $value) $ | quote }}
    {{- end }}
spec:
  rules:
    - host: {{ .Values.ingress.executor.domain }}
      http:
        paths:
          - path: {{ .Values.ingress.executor.path }}
            pathType: {{ .Values.ingress.executor.pathType }}
            backend:
              service:
                name: {{ .Values.name }}-executor-service
                port:
                  number: 8090
{{- end }}
{{- end }}