{{- if .Values.ingress.ui.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: terrakube-ui-ingress
  {{- with .Values.ingress.ui.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ default "nginx" .Values.ingress.ui.ingressClassName }}
  {{- if and .Values.ingress.useTls .Values.ingress.includeTlsHosts }}
  tls:
  - hosts:
    {{- range .Values.ingress.ui.domains }}
    - {{ . | quote }}
    {{- end }}
    secretName: {{ .Values.ingress.ui.tlsSecretName }}
  {{- end }}
  rules:
  {{- range .Values.ingress.ui.domains }}
  - host:  {{ . | quote }}
    http:
      paths:
      - path: {{ $.Values.ingress.ui.path | quote }}
        pathType: {{ $.Values.ingress.ui.pathType | quote }}
        backend:
          service:
            name: terrakube-ui-service
            port:
              number: 8080
  {{- end }}
{{ end }}