{{- if .Values.ingress.executor.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: terrakube-executor-ingress
  labels:
    {{- include "terrakube.labels" . | nindent 4 }}
  {{- with .Values.ingress.executor.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ default "nginx" .Values.ingress.executor.ingressClassName }}
  {{ if and .Values.ingress.useTls .Values.ingress.includeTlsHosts -}}
  tls:
  - hosts:
    - {{ .Values.ingress.executor.domain | quote }}
    secretName: {{ .Values.ingress.executor.tlsSecretName }}
  {{ end }}
  rules:
  - host:  {{ .Values.ingress.executor.domain | quote }}
    http:
      paths:
      - path: {{ .Values.ingress.executor.path | quote }}
        pathType: {{ .Values.ingress.executor.pathType | quote }}
        backend:
          service:
            name: terrakube-executor-service
            port:
              number: 8090
{{ end }}