{{- if not (and (eq .Values.ingress.controller "gke") .Values.ingress.gke.enabled .Values.ingress.use_single_loadbalancer) }}
{{- if .Values.ingress.ui.enabled }}
{{- if eq .Values.ingress.controller "generic" }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.name }}-ui
  labels:
    app: {{ .Values.name }}-ui
  {{- with .Values.ingress.ui.annotations }}
  annotations:
    {{- range $key, $value := . }}
    {{ $key }}: {{ tpl (toString $value) $ | quote }}
    {{- end }}
  {{- end }}
spec:
  {{- if .Values.ingress.ui.ingressClassName }}
  ingressClassName: {{ .Values.ingress.ui.ingressClassName }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.ui.domain }}
      http:
        paths:
          - path: {{ .Values.ingress.ui.path }}
            pathType: {{ .Values.ingress.ui.pathType }}
            backend:
              service:
                name: {{ .Values.name }}-ui-service
                port:
                  number: 8080
  {{- if .Values.ingress.useTls }}
  tls:
    - hosts:
      {{- if .Values.ingress.includeTlsHosts }}
        - {{ .Values.ingress.ui.domain }}
      {{- end }}
      secretName: {{ .Values.ingress.ui.tlsSecretName }}
  {{- end }}
{{- else if and (eq .Values.ingress.controller "aws") .Values.ingress.aws.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.name }}-ui
  labels:
    app: {{ .Values.name }}-ui
  annotations:
    # For AWS shared load balancer
    {{- if and .Values.ingress.aws.sharedLoadBalancer.enabled .Values.ingress.aws.sharedLoadBalancer.groupName }}
    alb.ingress.kubernetes.io/group.name: {{ .Values.ingress.aws.sharedLoadBalancer.groupName }}
    {{- end }}
    {{- range $key, $value := .Values.ingress.aws.annotations }}
    {{ $key }}: {{ tpl (toString $value) $ | quote }}
    {{- end }}
    {{- if .Values.ingress.aws.certificateArn }}
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.ingress.aws.certificateArn }}
    {{- end }}
    {{- range $key, $value := .Values.ingress.ui.annotations }}
    {{ $key }}: {{ tpl (toString $value) $ | quote }}
    {{- end }}
spec:
  rules:
    - host: {{ .Values.ingress.ui.domain }}
      http:
        paths:
          - path: {{ .Values.ingress.ui.path }}
            pathType: {{ .Values.ingress.ui.pathType }}
            backend:
              service:
                name: {{ .Values.name }}-ui-service
                port:
                  number: 8080
{{- else if and (eq .Values.ingress.controller "gke") .Values.ingress.gke.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.name }}-ui
  labels:
    app: {{ .Values.name }}-ui
  annotations:
    # GKE individual load balancer annotations (no shared IP)
    {{- if and .Values.ingress.gke.sharedLoadBalancer.enabled (not .Values.ingress.use_single_loadbalancer) }}
    {{- if .Values.ingress.gke.sharedLoadBalancer.staticIPName }}
    kubernetes.io/ingress.global-static-ip-name: {{ .Values.ingress.gke.sharedLoadBalancer.staticIPName }}-ui
    {{- end }}
    {{- end }}
    # Apply managed certificate if enabled
    {{- if .Values.ingress.gke.managedCertificate.create }}
    networking.gke.io/managed-certificates: {{ .Values.name }}-ui-certificate
    {{- end }}
    # Apply frontend config if enabled
    {{- if .Values.ingress.gke.frontendConfig.create }}
    networking.gke.io/v1beta1.FrontendConfig: {{ .Values.name }}-ui-frontend-config
    {{- end }}
    # Apply UI-specific backend config
    {{- if .Values.ingress.gke.backendConfig.create }}
    cloud.google.com/backend-config: '{"default": "{{ .Values.name }}-ui-backend-config"}'
    {{- end }}
    # Apply ExternalDNS proxy configuration
    {{- if .Values.ingress.gke.externalDNS }}
    {{- if .Values.ingress.gke.externalDNS.perIngressProxy }}
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "{{ .Values.ingress.gke.externalDNS.perIngressProxy.ui }}"
    {{- else }}
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "{{ .Values.ingress.gke.externalDNS.proxyEnabled }}"
    {{- end }}
    {{- end }}
    # GKE annotations
    {{- range $key, $value := .Values.ingress.gke.annotations }}
    {{ $key }}: {{ tpl (toString $value) $ | quote }}
    {{- end }}
    # UI specific annotations
    {{- range $key, $value := .Values.ingress.ui.annotations }}
    {{ $key }}: {{ tpl (toString $value) $ | quote }}
    {{- end }}
spec:
  ingressClassName: gce
  rules:
    - host: {{ .Values.ingress.ui.domain }}
      http:
        paths:
          - path: {{ .Values.ingress.ui.path }}
            pathType: {{ .Values.ingress.ui.pathType }}
            backend:
              service:
                name: {{ .Values.name }}-ui-service
                port:
                  number: 8080
{{- end }}
{{- end }}
{{- end }}