{{- if .Values.api.rbac.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.api.serviceAccountName }}
  labels:
    {{- include "terrakube.labels" . | nindent 4 }}
{{- with .Values.api.automountServiceAccountToken }}
automountServiceAccountToken: {{ . }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.api.rbac.roleName }}
  labels:
    {{- include "terrakube.labels" . | nindent 4 }}
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.api.rbac.roleBindingName }}
  labels:
    {{- include "terrakube.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.api.serviceAccountName }}
roleRef:
  kind: Role
  name: {{ .Values.api.rbac.roleName }}
  apiGroup: rbac.authorization.k8s.io
{{ end }}
