{{- if and .Values.security.useOpenLDAP (not .Values.security.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.security.ldapConfigSecretName }}
type: Opaque
stringData:
  config-ldap.ldif: |
    dn: {{ .Values.openldap.baseRoot }}
    dc: example
    objectClass: dcObject
    objectClass: organization
    o: Example, Inc

    dn: ou=users,{{ .Values.openldap.baseRoot }}
    ou: users
    objectClass: organizationalunit

    dn: cn={{ .Values.openldap.adminUser }},ou=users,{{ .Values.openldap.baseRoot }}
    objectClass: inetOrgPerson
    sn: Admin
    cn: Admin
    mail: admin@example.com
    userpassword: {{ .Values.openldap.adminPass }}

    dn: cn=grady,ou=users,{{ .Values.openldap.baseRoot }}
    objectClass: inetOrgPerson
    sn: Chambers
    cn: Grady
    mail: aws@example.com
    userpassword: aws

    dn: cn=saarah,ou=users,{{ .Values.openldap.baseRoot }}
    objectClass: inetOrgPerson
    sn: Lott
    cn: Saarah
    mail: azure@example.com
    userpassword: azure

    dn: cn=eugene,ou=users,{{ .Values.openldap.baseRoot }}
    objectClass: inetOrgPerson
    sn: Monaghan
    cn: Eugene
    mail: gcp@example.com
    userpassword: gcp

    # Group definitions.

    dn: ou=Groups,{{ .Values.openldap.baseRoot }}
    objectClass: organizationalUnit
    ou: Groups

    dn: cn=TERRAKUBE_ADMIN,ou=Groups,{{ .Values.openldap.baseRoot }}
    objectClass: groupOfNames
    cn: TERRAKUBE_ADMIN
    member: cn={{ .Values.openldap.adminUser }},ou=users,{{ .Values.openldap.baseRoot }}

    dn: cn=TERRAKUBE_DEVELOPERS,ou=Groups,{{ .Values.openldap.baseRoot }}
    objectClass: groupOfNames
    cn: TERRAKUBE_DEVELOPERS
    member: cn={{ .Values.openldap.adminUser }},ou=users,{{ .Values.openldap.baseRoot }}

    dn: cn=AZURE_DEVELOPERS,ou=Groups,{{ .Values.openldap.baseRoot }}
    objectClass: groupOfNames
    cn: AZURE_DEVELOPERS
    member: cn=saarah,ou=users,{{ .Values.openldap.baseRoot }}

    dn: cn=AWS_DEVELOPERS,ou=Groups,{{ .Values.openldap.baseRoot }}
    objectClass: groupOfNames
    cn: AWS_DEVELOPERS
    member: cn=grady,ou=users,{{ .Values.openldap.baseRoot }}

    dn: cn=GCP_DEVELOPERS,ou=Groups,{{ .Values.openldap.baseRoot }}
    objectClass: groupOfNames
    cn: GCP_DEVELOPERS
    member: cn=eugene,ou=users,{{ .Values.openldap.baseRoot }}

{{ end }}
