{{- if .Values.ui.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: terrakube-ui-secrets
type: Opaque
stringData:
  REACT_APP_TERRAKUBE_API_URL: 'https://{{ .Values.ingress.api.domain }}/api/v1/'
  REACT_APP_CLIENT_ID: '{{ .Values.security.dexClientId }}'
  REACT_APP_AUTHORITY: '{{ .Values.security.dexIssuerUri }}'
  REACT_APP_REDIRECT_URI: 'https://{{ .Values.ingress.ui.domain }}'
  REACT_APP_REGISTRY_URI: 'https://{{ .Values.ingress.registry.domain }}'
  REACT_APP_SCOPE: '{{ .Values.security.dexClientScope }}'
  env-config.js: |
    window._env_ = {
      REACT_APP_TERRAKUBE_API_URL: "https://{{ .Values.ingress.api.domain }}/api/v1/",
      REACT_APP_CLIENT_ID: "{{ .Values.security.dexClientId }}",
      REACT_APP_AUTHORITY: "{{ .Values.security.dexIssuerUri }}",
      REACT_APP_REDIRECT_URI: "https://{{ .Values.ingress.ui.domain }}",
      REACT_APP_REGISTRY_URI: "https://{{ .Values.ingress.registry.domain }}",
      REACT_APP_SCOPE: "{{ .Values.security.dexClientScope }}",
    }
{{ end }}