{{- if .Values.dex.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: terrakube-dex-secrets
type: Opaque
stringData:
  config.yaml: {{ .Values.dex.properties.config | toYaml | quote }}

  {{- if and (.Values.security).gcpCredentials }}
  gcp-credentials: {{ .Values.security.gcpCredentials | toJson }}
  {{- end }}
  
{{ end }}