apiVersion: v1
kind: Secret
metadata:
  name: terrakube-ca-secrets
  labels:
    {{- include "terrakube.labels" . | nindent 4 }}
type: Opaque
stringData: 
  type: |
    ca-certificates
  
  {{- with .Values.security.caCerts }}
  {{- toYaml . | nindent 2 }}
  {{- end }}