{{- if .Values.ui.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: terrakube-ui-secrets
type: Opaque
stringData:
  # This UI configuration file is loaded in /app/env-config.js
  env-config.js: |
    window._env_ = {
      REACT_APP_TERRAKUBE_API_URL: "{{- if .Values.ingress.useTls }}https{{else}}http{{ end }}://{{ .Values.ingress.api.domain }}/api/v1/",
      REACT_APP_CLIENT_ID: "{{ .Values.security.dexClientId }}",
      REACT_APP_AUTHORITY: "{{ .Values.dex.config.issuer }}",
      REACT_APP_REDIRECT_URI: "{{- if .Values.ingress.useTls }}https{{else}}http{{ end }}://{{ .Values.ingress.ui.domain }}",
      REACT_APP_REGISTRY_URI: "{{- if .Values.ingress.useTls }}https{{else}}http{{ end }}://{{ .Values.ingress.registry.domain }}",
      REACT_APP_SCOPE: "{{ .Values.security.dexClientScope }}",
    }
{{ end }}