apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-dex
  labels:
    app: dex
    {{- include "terrakube.labels" . | nindent 4 }}
  {{- if and (eq .Values.ingress.controller "gke") .Values.ingress.gke.enabled .Values.ingress.gke.backendConfig.create }}
  annotations:
    cloud.google.com/backend-config: '{"default": "{{ .Values.name }}-dex-backend-config"}'
    cloud.google.com/neg: '{"ingress": true}'
  {{- end }}
spec:
  # Already defined in the Dex chart
  ports:
    - name: http
      port: 5556
      targetPort: 5556