{{- if .Values.executor.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: terrakube-executor-service
  labels:
    {{- include "terrakube.labels" . | nindent 4 }}
spec:
  type: {{ .Values.executor.serviceType }}
  ports:
  - port: 8090
    targetPort: 8090
  selector:
    {{- include "terrakube-executor.labels" . | nindent 4 }}
{{ end }}