{{- if .Values.registry.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: terrakube-registry-service
  labels:
    {{- include "terrakube.labels" . | nindent 4 }}
spec:
  type: {{ .Values.registry.serviceType }}
  ports:
  - port: 8075
    targetPort: 8075
  selector:
    {{- include "terrakube-registry.labels" . | nindent 4 }}
{{ end }}