{{- if .Values.ui.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: terrakube-ui-service
  labels:
    {{- include "terrakube.labels" . | nindent 4 }}
spec:
  type: {{ .Values.ui.serviceType }}
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    {{- include "terrakube-ui.labels" . | nindent 4 }}
{{ end }}