{{- if .Values.executor.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: terrakube-executor-service
  labels:
    {{- include "terrakube.labels" . | nindent 4 }}
spec:
  type: {{ .Values.executor.serviceType }}
  ports:
  - port: 8090
    targetPort: http
{{- if and .Values.executor.otel.enabled .Values.executor.otel.metrics }}
  - port: {{ .Values.executor.otel.metrics.port | default "9464" }}
    targetPort: metrics
{{- end }}
  selector:
    {{- include "terrakube-executor.labels" . | nindent 4 }}
{{ end }}
