{{- if .Values.dex.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: terrakube-dex-service
spec:
  type: {{ .Values.dex.serviceType }}
  ports:
  - port: 5556
    targetPort: 5556
  selector:
    app: terrakube-dex
{{ end }}