{{- if .Values.security.useOpenLDAP -}}
apiVersion: v1
kind: Service
metadata:
  name: terrakube-openldap-service 
spec:
  type: "ClusterIP"
  ports:
  - port: 389
    targetPort: 389
  selector:
    app: terrakube-openldap
{{ end }}