{{- if .Values.executor.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: terrakube-executor-service 
spec:
  type: {{ .Values.executor.serviceType }}
  ports:
  - port: 8090
    targetPort: 8090
  selector:
    app: terrakube-executor
{{ end }}