{{- if .Values.registry.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: terrakube-registry-service
  labels:
    {{- include "terrakube.labels" . | nindent 4 }}
spec:
  type: {{ .Values.registry.serviceType }}
  ports:
  - port: 8075
    targetPort: http
{{- if and .Values.registry.otel.enabled .Values.registry.otel.metrics }}
  - port: {{ .Values.registry.otel.metrics.port | default "9464" }}
    targetPort: metrics
{{- end }}
  selector:
    {{- include "terrakube-registry.labels" . | nindent 4 }}
{{ end }}
