{{- if .Values.api.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: terrakube-api-service
  labels:
    {{- include "terrakube.labels" . | nindent 4 }}
spec:
  type: {{ .Values.api.serviceType }}
  ports:
  - port: 8080
    targetPort: http
{{- if and .Values.api.otel.enabled .Values.api.otel.metrics }}
  - port: {{ .Values.api.otel.metrics.port | default "9464" }}
    targetPort: metrics
{{- end }}
  selector:
    {{- include "terrakube-api.labels" . | nindent 4 }}
{{ end }}
