{{- if .Values.api.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: terrakube-api-service
spec:
  type: {{ .Values.api.serviceType }}
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: terrakube-api
{{ end }}