{{- if .Values.security.useOpenLDAP -}}
apiVersion: v1
kind: Service
metadata:
  name: terrakube-openldap-service
  labels:
    {{- include "terrakube.labels" . | nindent 4 }}
spec:
  type: "ClusterIP"
  ports:
  - port: 1389
    targetPort: 1389
  selector:
    {{- include "terrakube-openldap.labels" . | nindent 4 }}
{{ end }}