{{- if .Values.executor.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: terrakube-executor
  labels:
    app: terrakube-executor
spec:
  replicas: {{ .Values.executor.replicaCount }}
  selector:
    matchLabels:
      app: terrakube-executor
  template:
    metadata:
      labels:
        app: terrakube-executor
    spec:
      containers:
      - name: terrakube-executor
        image: azbuilder/executor:{{ .Values.executor.version }}
        {{- if .Values.executor.resources }}
        resources: {{- toYaml .Values.executor.resources | nindent 12 }}
        {{- end }}
        ports:
        - containerPort: 8090
        envFrom:
        - secretRef:
            name: terrakube-executor-secrets
        startupProbe:
          httpGet:
            path: /actuator/health
            port: 8090
          failureThreshold: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8090
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8090
          initialDelaySeconds: 120
          periodSeconds: 10
      {{- with .Values.executor.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.executor.tolerations }}
      tolerations:
        {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.executor.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{ end }}