{{- if .Values.registry.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: terrakube-registry
  labels:
    app: terrakube-registry
spec:
  replicas: {{ .Values.registry.replicaCount }}
  selector:
    matchLabels:
      app: terrakube-registry
  template:
    metadata:
      labels:
        app: terrakube-registry
    spec:
      containers:
      - name: terrakube-registry
        image: azbuilder/open-registry:{{ .Values.registry.version }}
        {{- if .Values.registry.resources }}
        resources: {{- toYaml .Values.registry.resources | nindent 12 }}
        {{- end }}
        ports:
        - containerPort: 8075
        envFrom:
        - secretRef:
            name: terrakube-registry-secrets
        startupProbe:
          httpGet:
            path: /actuator/health
            port: 8075
          failureThreshold: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8075
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8075
          initialDelaySeconds: 120
          periodSeconds: 10
      {{- with .Values.registry.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.registry.tolerations }}
      tolerations:
        {{- toYaml . | nindent 6 }}
      {{- end }}
{{ end }}