{{- if .Values.ingress.ui.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: terrakube-ui-ingress
  {{- with .Values.ingress.ui.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{ if .Values.ingress.useTls }}
  tls:
  - hosts:
    - {{ .Values.ingress.ui.domain | quote }}
    secretName: tls-secret-ui-terrakube
  {{ end }}
  rules:
  - host:  {{ .Values.ingress.ui.domain | quote }}
    http:
      paths:
      - path: {{ .Values.ingress.ui.path | quote }} 
        pathType: {{ .Values.ingress.ui.pathType | quote }}
        backend:
          service:
            name: terrakube-ui-service
            port:
              number: 8080
{{ end }}