{{- if .Values.ingress.api.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: terrakube-api-ingress
  {{- with .Values.ingress.api.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{ if .Values.ingress.useTls }}
  tls:
  - hosts:
    - {{ .Values.ingress.api.domain | quote }}
    secretName: tls-secret-terrakube
  {{ end }}
  rules:
  - host: {{ .Values.ingress.api.domain | quote }}
    http:
      paths:
      - path: /service(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: terrakube-api-service
            port:
              number: 8080
      - path: /open-registry(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: terrakube-registry-service
            port:
              number: 8075
{{ end }}