apiVersion: v1
kind: Secret
metadata:
  name: terrakube-api-secrets
  namespace: {{ .Values.name }}
type: Opaque
stringData:
  ApiDataSourceType: '{{ .Values.databaseType }}'
  AzureAdAppId: '{{ .Values.azureAppClientId }}'
  AzureAdApiIdUri: '{{ .Values.azureAppIdURI }}'
  GroupValidationType: '{{ .Values.securityType }}'
  UserValidationType: '{{ .Values.securityType }}'
  AuthenticationValidationType: '{{ .Values.securityType }}'
  AzGroupClientId: '{{ .Values.azureAppClientId }}'
  AzGroupTenantId: '{{ .Values.azureAppTenantId }}'
  AzGroupSecret: '{{ .Values.azureAppSecret }}'
  DatasourceHostname: '{{ .Values.datasourceHostname }}'
  DatasourceDatabase: '{{ .Values.datasourceDatabase }}'
  DatasourceUser: '{{ .Values.datasourceUser }}'
  DatasourcePassword: '{{ .Values.datasourcePassword }}' 
  TerrakubeHostname: '{{ .Values.apiDomain }}/service'
  AzBuilderExecutorUrl: 'http://terrakube-executor-service:8090/api/v1/terraform-rs'
---
apiVersion: v1
kind: Secret
metadata:
  name: terrakube-executor-secrets
  namespace: {{ .Values.name }}
type: Opaque
stringData:
  TerraformStateType: '{{ .Values.terraformStateType }}'
  AzureTerraformStateResourceGroup: '{{ .Values.azureStorageAccountResourceGroup }}'
  AzureTerraformStateStorageAccountName: '{{ .Values.azureStorageAccountName }}'
  AzureTerraformStateStorageContainerName: 'tfstate'
  AzureTerraformStateStorageAccessKey: '{{ .Values.azureStorageAccountAccessKey }}'
  TerraformOutputType: '{{ .Values.terraformOutputType }}'
  AzureTerraformOutputAccountName: '{{ .Values.azureStorageAccountName }}'
  AzureTerraformOutputAccountKey: '{{ .Values.azureStorageAccountAccessKey }}'
  AzBuilderApiUrl: 'http://terrakube-api-service:8080'
  AzureAdAppClientId: '{{ .Values.azureAppClientId }}'
  AzureAdAppClientSecret: '{{ .Values.azureAppSecret }}'
  AzureAdAppTenantId: '{{ .Values.azureAppTenantId }}'
  AzureAdAppScope: '{{ .Values.azureAppIdURI }}/.default'
  ExecutorFlagBatch: 'false'
  ExecutorFlagDisableAcknowledge: 'false'
  TerrakubeToolsRepository: 'https://github.com/AzBuilder/terrakube-extensions'
  TerrakubeToolsBranch: 'main'
  TerrakubeEnableSecurity: 'true'
  TerrakubeRegistryDomain: '{{ .Values.registryDomain }}'
---
apiVersion: v1
kind: Secret
metadata:
  name: terrakube-registry-secrets
  namespace: {{ .Values.name }}
type: Opaque
stringData:
  AzBuilderRegistry: 'https://{{ .Values.apiDomain }}/open-registry'
  AzureAccountName: '{{ .Values.azureStorageAccountName }}'
  AzureAccountKey: '{{ .Values.azureStorageAccountAccessKey }}'
  AzBuilderApiUrl: 'http://terrakube-api-service:8080'
  AzureAdAppClientId: '{{ .Values.azureAppClientId }}'
  AzureAdAppClientSecret: '{{ .Values.azureAppSecret }}'
  AzureAdAppTenantId: '{{ .Values.azureAppTenantId }}'
  AzureAdAppScope: '{{ .Values.azureAppIdURI }}/.default'
  AuthenticationValidationTypeRegistry: 'AZURE'
  TerrakubeEnableSecurity: 'true'
  AzureAdAppId: '{{ .Values.azureAppClientId }}'
  AzureAdApiIdUri: '{{ .Values.azureAppIdURI }}'
---
apiVersion: v1
kind: Secret
metadata:
  name: terrakube-ui-secrets
  namespace: {{ .Values.name }}
type: Opaque
stringData:
  REACT_APP_TERRAKUBE_API_URL: 'http{{ if .Values.enableTLS }}s{{ end }}://{{ .Values.apiDomain }}/service/api/v1/'
  REACT_APP_CLIENT_ID: '{{ .Values.azureAppClientId }}'
  REACT_APP_AUTHORITY: 'https://login.microsoftonline.com/{{ .Values.azureAppTenantId }}'
  REACT_APP_REDIRECT_URI: 'http{{ if .Values.enableTLS }}s{{ end }}://{{ .Values.uiDomain }}'
  REACT_APP_REGISTRY_URI: 'http{{ if .Values.enableTLS }}s{{ end }}://{{ .Values.registryDomain }}'
  REACT_APP_SCOPE: '{{ .Values.azureAppIdURI }}/Builder.Default'
