apiVersion: v1
kind: Secret
metadata:
  name: terrakube-api-secrets
  namespace: {{ .Values.name }}-ns
type: Opaque
stringData:
  ApiDataSourceType: '{{ .Values.databaseType }}'
  AzureAdAppId: '{{ .Values.azureAppClientId }}'
  AzureAdApiIdUri: 'api://{{ .Values.name }}'
  GroupValidationType: '{{ .Values.securityType }}'
  UserValidationType: '{{ .Values.securityType }}'
  AuthenticationValidationType: '{{ .Values.securityType }}'
  AzGroupClientId: '{{ .Values.azureAppClientId }}'
  AzGroupTenantId: '{{ .Values.azureAppTenantId }}'
  AzGroupSecret: '{{ .Values.azureAppSecret }}'
  DatasourceHostname: '{{ .Values.datasourceHostname }}'
  DatasourceDatabase: '{{ .Values.datasourceDatabase }}'
  DatasourceUser: '{{ .Values.datasourceUser }}'
  DatasourcePassword: '{{ .Values.datasourcePassword }}' 
  TerrakubeHostname: '{{ .Values.apiDomain }}/{{ .Values.apiPath }}'
  AzBuilderExecutorUrl: 'http://terrakube-executor-service:8090/api/v1/terraform-rs'
---
apiVersion: v1
kind: Secret
metadata:
  name: terrakube-executor-secrets
  namespace: {{ .Values.name }}-ns
type: Opaque
stringData:
  TerraformStateType: '{{ .Values.terraformStateType }}'
  AzureTerraformStateResourceGroup: '{{ .Values.azureStorageAccountResourceGroup }}'
  AzureTerraformStateStorageAccountName: '{{ .Values.azureStorageAccountName }}'
  AzureTerraformStateStorageContainerName: 'tfstate'
  AzureTerraformStateStorageAccessKey: '{{ .Values.azureStorageAccountAccessKey }}'
  TerraformOutputType: '{{ .Values.terraformOutputType }}'
  AzureTerraformOutputAccountName: '{{ .Values.azureStorageAccountName }}'
  AzureTerraformOutputAccountKey: '{{ .Values.azureStorageAccountAccessKey }}'
  AzBuilderApiUrl: 'http://terrakube-api-service:8080'
  AzureAdAppClientId: '{{ .Values.azureAppClientId }}'
  AzureAdAppClientSecret: '{{ .Values.azureAppSecret }}'
  AzureAdAppTenantId: '{{ .Values.azureAppTenantId }}'
  AzureAdAppScope: 'api://{{ .Values.name }}/.default'
  ExecutorFlagBatch: 'false'
  ExecutorFlagDisableAcknowledge: 'false'
  TerrakubeToolsRepository: 'https://github.com/AzBuilder/terrakube-extensions'
  TerrakubeToolsBranch: 'main'
  TerrakubeEnableSecurity: 'true'
  TerrakubeRegistryDomain: '{{ .Values.registryDomain }}'
---
apiVersion: v1
kind: Secret
metadata:
  name: terrakube-registry-secrets
  namespace: {{ .Values.name }}-ns
type: Opaque
stringData:
  AzBuilderRegistry: 'https://{{ .Values.apiDomain }}/open-registry'
  AzureAccountName: '{{ .Values.azureStorageAccountName }}'
  AzureAccountKey: '{{ .Values.azureStorageAccountAccessKey }}'
  AzBuilderApiUrl: 'http://terrakube-api-service:8080'
  AzureAdAppClientId: '{{ .Values.azureAppClientId }}'
  AzureAdAppClientSecret: '{{ .Values.azureAppSecret }}'
  AzureAdAppTenantId: '{{ .Values.azureAppTenantId }}'
  AzureAdAppScope: 'api://{{ .Values.name }}/.default'
  AuthenticationValidationTypeRegistry: 'AZURE'
  TerrakubeEnableSecurity: 'true'
  AzureAdAppId: '{{ .Values.azureAppClientId }}'
  AzureAdApiIdUri: 'api://{{ .Values.name }}'