{{- if .Values.api.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: terrakube-api-secrets
type: Opaque
stringData:
  ApiDataSourceType: '{{ .Values.api.properties.databaseType }}'
  AzureAdAppId: '{{ .Values.security.azure.appClientId }}'
  AzureAdApiIdUri: '{{ .Values.security.azure.appIdURI }}'
  GroupValidationType: '{{ .Values.security.type }}'
  UserValidationType: '{{ .Values.security.type }}'
  AuthenticationValidationType: '{{ .Values.security.type }}'
  AzGroupClientId: '{{ .Values.security.azure.appClientId }}'
  AzGroupTenantId: '{{ .Values.security.azure.appTenantId }}'
  AzGroupSecret: '{{ .Values.security.azure.appSecret }}'
  DatasourceHostname: '{{ .Values.api.properties.databaseHostname }}'
  DatasourceDatabase: '{{ .Values.api.properties.databaseName }}'
  DatasourceUser: '{{ .Values.api.properties.databaseUser }}'
  DatasourcePassword: '{{ .Values.api.properties.databasePassword }}' 
  TerrakubeHostname: '{{ .Values.ingress.api.domain }}'
  AzBuilderExecutorUrl: 'http://terrakube-executor-service:8090/api/v1/terraform-rs'
  TerrakubeUiURL: 'https://{{ .Values.ingress.ui.domain }}'
{{ end }}