{{- if .Values.registry.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: terrakube-registry-secrets
type: Opaque
stringData:
  AzBuilderRegistry: 'https://{{ .Values.ingress.api.domain }}/open-registry'
  AzureAccountName: '{{ .Values.storage.azure.storageAccountName }}'
  AzureAccountKey: '{{ .Values.storage.azure.storageAccountAccessKey }}'
  AzBuilderApiUrl: 'http://terrakube-api-service:8080'
  AzureAdAppClientId: '{{ .Values.security.azure.appClientId }}'
  AzureAdAppClientSecret: '{{ .Values.security.azure.appSecret }}'
  AzureAdAppTenantId: '{{ .Values.security.azure.appTenantId }}'
  AzureAdAppScope: '{{ .Values.security.azure.appIdURI }}/.default'
  AuthenticationValidationTypeRegistry: 'AZURE'
  TerrakubeEnableSecurity: 'true'
  AzureAdAppId: '{{ .Values.security.azure.appClientId }}'
  AzureAdApiIdUri: '{{ .Values.security.azure.appIdURI }}'
{{ end }}