{{- if .Values.dex.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: terrakube-dex-secrets
type: Opaque
data:
  config.yaml: {{ .Values.dex.properties.config | toYaml | b64enc | quote }}
  
{{ end }}