{{- if .Values.api.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: terrakube-api-secrets
type: Opaque
stringData:
  ApiDataSourceType: '{{ .Values.api.properties.databaseType }}'

  TERRAKUBE_ADMIN_GROUP: '{{ .Values.security.adminGroup }}'
  
  GroupValidationType: 'DEX'
  UserValidationType: 'DEX'
  AuthenticationValidationType: 'DEX'
  PatSecret: '{{ .Values.security.patSecret | b64enc }}'
  InternalSecret: '{{ .Values.security.internalSecret | b64enc }}'
  DexIssuerUri: '{{ .Values.security.dexIssuerUri }}'
  
  DatasourceHostname: '{{ .Values.api.properties.databaseHostname }}'
  DatasourceDatabase: '{{ .Values.api.properties.databaseName }}'
  DatasourceUser: '{{ .Values.api.properties.databaseUser }}'
  DatasourcePassword: '{{ .Values.api.properties.databasePassword }}' 
  TerrakubeHostname: '{{ .Values.ingress.api.domain }}'
  AzBuilderExecutorUrl: 'http://terrakube-executor-service:8090/api/v1/terraform-rs'
  TerrakubeUiURL: 'https://{{ .Values.ingress.ui.domain }}'
  
  {{- if and (.Values.storage.azure).storageAccountName (.Values.storage.azure).storageAccountAccessKey }}
  #Azure Storage
  StorageType: 'AZURE'
  AzureAccountName: '{{ .Values.storage.azure.storageAccountName }}'
  AzureAccountKey: '{{ .Values.storage.azure.storageAccountAccessKey }}'
  {{- end }}
  
  {{- if and (.Values.storage.aws).bucketName (.Values.storage.aws).accessKey (.Values.storage.aws).secretKey (.Values.storage.aws).region  }}
  #AWS S3 Storage
  StorageType: 'AWS'
  AwsStorageAccessKey: '{{ .Values.storage.aws.accessKey }}'
  AwsStorageSecretKey: '{{ .Values.storage.aws.secretKey }}'
  AwsStorageBucketName: '{{ .Values.storage.aws.bucketName }}'
  AwsStorageRegion: '{{ .Values.storage.aws.region }}'
  {{- end }}

  {{- if and (.Values.storage.gcp).projectId (.Values.storage.gcp).bucketName (.Values.storage.gcp).credentials  }}
  #GCP Storage Bucket
  StorageType: 'GCP'
  GcpStorageProjectId: '{{ .Values.storage.gcp.projectId }}'
  GcpStorageBucketName: '{{ .Values.storage.gcp.bucketName }}'
  GcpStorageCredentialsBase64: {{ .Values.storage.gcp.credentials | b64enc }}
  {{- end }}
{{ end }}