{{- if .Values.executor.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: terrakube-executor-secrets
type: Opaque
stringData:
  TerraformStateType: '{{ .Values.executor.properties.terraformStateType }}'
  AzureTerraformStateResourceGroup: '{{ .Values.storage.azure.storageAccountResourceGroup }}'
  AzureTerraformStateStorageAccountName: '{{ .Values.storage.azure.storageAccountName }}'
  AzureTerraformStateStorageContainerName: 'tfstate'
  AzureTerraformStateStorageAccessKey: '{{ .Values.storage.azure.storageAccountAccessKey }}'
  TerraformOutputType: '{{ .Values.executor.properties.terraformOutputType }}'
  AzureTerraformOutputAccountName: '{{ .Values.storage.azure.storageAccountName }}'
  AzureTerraformOutputAccountKey: '{{ .Values.storage.azure.storageAccountAccessKey }}'
  AzBuilderApiUrl: 'http://terrakube-api-service:8080'
  AzureAdAppClientId: '{{ .Values.security.azure.appClientId }}'
  AzureAdAppClientSecret: '{{ .Values.security.azure.appSecret }}'
  AzureAdAppTenantId: '{{ .Values.security.azure.appTenantId }}'
  AzureAdAppScope: '{{ .Values.security.azure.appIdURI }}/.default'
  ExecutorFlagBatch: 'false'
  ExecutorFlagDisableAcknowledge: 'false'
  TerrakubeToolsRepository: '{{ .Values.executor.properties.toolsRepository }}'
  TerrakubeToolsBranch: '{{ .Values.executor.properties.toolsBranch }}'
  TerrakubeEnableSecurity: 'true'
  TerrakubeRegistryDomain: '{{ .Values.ingress.registry.domain }}'
{{ end }}