{{- if .Values.executor.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: terrakube-executor-secrets
type: Opaque
stringData:
  # State/Output Type
  TerraformStateType: '{{ .Values.executor.properties.terraformStateType }}'
  TerraformOutputType: '{{ .Values.executor.properties.terraformOutputType }}'
  
  # General Settings
  AzBuilderApiUrl: 'http://terrakube-api-service:8080'
  AzureAdAppClientId: '{{ .Values.security.azure.appClientId }}'
  AzureAdAppClientSecret: '{{ .Values.security.azure.appSecret }}'
  AzureAdAppTenantId: '{{ .Values.security.azure.appTenantId }}'
  AzureAdAppScope: '{{ .Values.security.azure.appIdURI }}/.default'
  ExecutorFlagBatch: 'false'
  ExecutorFlagDisableAcknowledge: 'false'
  TerrakubeToolsRepository: '{{ .Values.executor.properties.toolsRepository }}'
  TerrakubeToolsBranch: '{{ .Values.executor.properties.toolsBranch }}'
  TerrakubeEnableSecurity: 'true'
  TerrakubeRegistryDomain: '{{ .Values.ingress.registry.domain }}'
  TerrakubeApiUrl: 'https://{{ .Values.ingress.api.domain }}'
  
  {{- if eq .Values.executor.properties.terraformStateType "AzureTerraformStateImpl" }}
  #Azure Storage State
  AzureTerraformStateResourceGroup: '{{ .Values.storage.azure.storageAccountResourceGroup }}'
  AzureTerraformStateStorageAccountName: '{{ .Values.storage.azure.storageAccountName }}'
  AzureTerraformStateStorageContainerName: 'tfstate'
  AzureTerraformStateStorageAccessKey: '{{ .Values.storage.azure.storageAccountAccessKey }}'
  {{- end }}
  
  {{- if eq .Values.executor.properties.terraformOutputType "AzureTerraformOutputImpl" }}
  #Azure Storage Output
  AzureTerraformOutputAccountName: '{{ .Values.storage.azure.storageAccountName }}'
  AzureTerraformOutputAccountKey: '{{ .Values.storage.azure.storageAccountAccessKey }}'
  {{- end }}
  
  {{- if eq .Values.executor.properties.terraformStateType "AwsTerraformStateImpl" }}
  #AWS S3 State
  AwsTerraformStateAccessKey: '{{ .Values.storage.aws.accessKey }}'
  AwsTerraformStateSecretKey: '{{ .Values.storage.aws.secretKey }}'
  AwsTerraformStateBucketName: '{{ .Values.storage.aws.bucketName }}'
  AwsTerraformStateRegion: '{{ .Values.storage.aws.region }}'
  {{- end }}

  {{- if eq .Values.executor.properties.terraformOutputType "AwsTerraformOutputImpl" }}
  #AWS S3 Output
  AwsTerraformOutputAccessKey: '{{ .Values.storage.aws.accessKey }}'
  AwsTerraformOutputSecretKey: '{{ .Values.storage.aws.secretKey }}'
  AwsTerraformOutputBucketName: '{{ .Values.storage.aws.bucketName }}'
  AwsTerraformOutputRegion: '{{ .Values.storage.aws.region }}'
  {{- end }}
{{ end }}