{{- if .Values.ui.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: terrakube-ui-secrets
type: Opaque
stringData:
  REACT_APP_TERRAKUBE_API_URL: 'https://{{ .Values.ingress.api.domain }}/api/v1/'
  REACT_APP_CLIENT_ID: '{{ .Values.security.azure.appClientId }}'
  REACT_APP_AUTHORITY: 'https://login.microsoftonline.com/{{ .Values.security.azure.appTenantId }}'
  REACT_APP_REDIRECT_URI: 'https://{{ .Values.ingress.ui.domain }}'
  REACT_APP_REGISTRY_URI: 'https://{{ .Values.ingress.registry.domain }}'
  REACT_APP_SCOPE: '{{ .Values.security.azure.appIdURI }}/Builder.Default'
{{ end }}