{{- if .Values.ui.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: terrakube-ui-service
spec:
  type: {{ .Values.ui.serviceType }}
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: terrakube-ui
{{ end }}